version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: graphql-go
        ports:
            - "8080:8080"
        links:
            - db:db
        depends_on:
            - db
        environment:
            DB_HOST: "192.168.99.100"
            DB_PORT: "5432"
            DB_USER: "postgres"
            DB_PWD: "postgres"
            DB_NAME: "graphql"


    db:
        build:
            context: .
            dockerfile: Dockerfile-db
        image: postgres-graphql
        # Just for tests, to check if tables are getting populated correctly
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: "postgres"
            DB_NAME: "graphql"
